version: "3.8"
services:
    dsgn2:
        image: ${ARCH}dsgn2:${TAG}
        build:
            context: ${PRODUCTION_PATH}
            dockerfile: Dockerfile.${ARCH}
        container_name: dsgn2
        tty: true
