version: "3.8"
services:
    jetson-app:
        image: ${ARCH}dsgn2:${TAG}
        network_mode: host
        pid: host
        container_name: dsgn2
        env_file: $ENV_FILE
        environment:
            - DISPLAY=$DISPLAY
        privileged: true
        tty: true
        volumes:
            - type: bind
              source: ${PRODUCTION_PATH}/../data
              target: /home/dsgn2/DSGN2/data
            - /dev:/dev:rw
            - /dev:/dev \
        command: /bin/sh --login
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]
