version: "3.8"
services:
    jetson-app:
        image: ${ARCH}dsgn2:${TAG}
        network_mode: host
        pid: host
        container_name: dsgn2
        env_file: $ENV_FILE
        environment:
            - DISPLAY=$DISPLAY
        privileged: true
        user: root
        tty: true
        volumes:
            - type: bind
              source: ${PRODUCTION_PATH}/../DSGN2
              target: /home/dsgn2/
            - /dev:/dev:rw
            - /dev:/dev \
        command: /bin/sh --login
